site_name: Srikanth M
nav:
  - Home: index.md
  - Projects: projects.md

#theme:
 # name: material  # Optional, looks clean
theme:
  name: material
  palette:
    scheme: dark  # or default/light/dark
    primary: white
    accent: green

extra_css:
  - stylesheets/custom.css

